name: Build IronAge plugin

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Compiler avec Maven
        working-directory: ironage-plugin
        run: mvn -B clean package

      - name: Publier le .jar compile
        uses: actions/upload-artifact@v4
        with:
          name: ironage-plugin-jar
          path: ironage-plugin/target/*.jar
